language: python
sudo: required
dist: xenial
python: "3.7"

before_install:
  - git submodule update --init --recursive
  - nvm install node
  - make harness-populate
install: make install-dev
script:
  - make test
  - make lint

notifications:
  email: false
